language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '8' # using async/await and stuff
  - '10'
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
