project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
commit_message: 'feat: new translations'
preserve_hierarchy: true
files:
  - source: /content/en-US/docs/*.md
    translation: /content/%locale%/docs/%original_file_name%
  - source: /content/en-US/docs/development/*.md
    translation: /content/%locale%/docs/development/%original_file_name%
  - source: /content/en-US/docs/tutorial/*.md
    translation: /content/%locale%/docs/tutorial/%original_file_name%
  - source: /content/en-US/docs/api/*.md
    translation: /content/%locale%/docs/api/%original_file_name%
  - source: /content/en-US/docs/api/structures/*.md
    translation: /content/%locale%/docs/api/structures/%original_file_name%
  - source: /content/en-US/website/blog/*.md
    translation: /content/%locale%/website/blog/%original_file_name%
  - source: /content/en-US/website/*.yml
    translation: /content/%locale%/website/%original_file_name%
  - source: /content/en-US/website/i18n/**/*.json
    translation: /content/%locale%/website/i18n/**/%original_file_name%
