###############################################
# THIS FILE IS AUTOMATICALLY GENERATED FROM   #
# lib/generators/templates/auto-merge.yml.tpl #
###############################################

on:
  schedule:
    - cron: 00 09 * * *
  workflow_dispatch: {}

name: Auto-merge Crowdin PRs

jobs:
  auto-merge:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm ci
      - name: Automerge PR
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run automerge
