#############################################
# THIS FILE IS AUTOMATICALLY GENERATED FROM #
# lib/generators/templates/crowin.yml.tpl   #
#############################################

commit_message: 'feat: new translations'
preserve_hierarchy: true
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

files:
  - source: /content/en-US/docs/*.md
    translation: /content/%locale%/docs/%original_file_name%
  - source: /content/en-US/docs/development/*.md
    translation: /content/%locale%/docs/development/%original_file_name%
  - source: /content/en-US/docs/tutorial/*.md
    translation: /content/%locale%/docs/tutorial/%original_file_name%
  - source: /content/en-US/docs/api/*.md
    translation: /content/%locale%/docs/api/%original_file_name%
  - source: /content/en-US/docs/api/structures/*.md
    translation: /content/%locale%/docs/api/structures/%original_file_name%

  # # Website Content
  # - source: /content/current/en-US/website/blog/*.md
  #   translation: /content/current/%locale%/website/blog/%original_file_name%
  # - source: /content/current/en-US/website/*.yml
  #   translation: /content/current/%locale%/website/%original_file_name%
