#############################################
# THIS FILE IS AUTOMATICALLY GENERATED FROM #
# lib/generators/templates/subrepos.yml.tpl #
#############################################

{{#each versions}}
- name: i18n/{{this}}
  directory: temp/i18n-{{this}}
  url: https://vhashimotoo:GH_TOKEN@github.com/vhashimotoo/i18n-jrti.git
  branch: content/{{this}}
{{/each}}
