# THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT MANUALLY

commit_message: 'feat: new translations'
preserve_hierarchy: true
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

files:
  {{#each versions}}
  # Content generate for version: "{{this}}"
  - source: /content/{{this}}/en-US/docs/*.md
    translation: /content/{{this}}/%locale%/docs/%original_file_name%
  - source: /content/{{this}}/en-US/docs/development/*.md
    translation: /content/{{this}}/%locale%/docs/development/%original_file_name%
  - source: /content/{{this}}/en-US/docs/tutorial/*.md
    translation: /content/{{this}}/%locale%/docs/tutorial/%original_file_name%
  - source: /content/{{this}}/en-US/docs/api/*.md
    translation: /content/{{this}}/%locale%/docs/api/%original_file_name%
  - source: /content/{{this}}/en-US/docs/api/structures/*.md
    translation: /content/{{this}}/%locale%/docs/api/structures/%original_file_name%
  {{/each}}

  # Website Content
  - source: /content/current/en-US/website/blog/*.md
    translation: /content/current/%locale%/website/blog/%original_file_name%
  - source: /content/current/en-US/website/*.yml
    translation: /content/current/%locale%/website/%original_file_name%
