on: push

name: CI / Only Tests (TEMPORARY)

jobs:
  onlytests:
    name: CI / Only Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: 'npm ci'
    - name: Run tests
      env:
        NODE_OPTIONS: --max_old_space_size=4096
      run: 'npm test'
